### ISSUE TITLE
File names in repository and file names in README do not match

### ISSUE THREAD

**Issue by julie-tran** [harcourt-rebecca/eep153-proj4#2] opened 2019-05-01 21:41 UTC
There are several files in the repository that have similar names. They also do not match the file names referenced in the README.

**Comment by liandy52** [comment] 2019-05-01 21:43
The dataset, "TanzanianNPS/tanzanian_nps.ds," is missing in your file "Project-4-example_nutrition-prof.-data (1).ipynb."

**Comment by lec97** [comment] 2019-05-01 21:48
> There are several files in the repository that have similar names. They also do not match the file names referenced in the README.

It looks like the issue is fixed now

**Comment by liandy52** [comment] 2019-05-01 21:52
The dataset is unreferenced to in "example_demands (2), example_nutrition, pt 1-Tanzanian Demands, pt-2-example_nutrition, and pt-4-Project-4-example_costs2." It prevents other codes from running.

**Comment by liandy52** [comment] 2019-05-01 21:59
File b'fct-full-fct-full.csv' does not exist in "pt 3-example_costs."

**Comment by julie-tran** [comment] 2019-05-01 22:01
I believe this is a different issue than the one mentioned in the heading above^. The dataset, "TanzanianNPS/tanzanian_nps.ds", is too large to upload to GitHub. Please follow this [link ](http://datahub.berkeley.edu/user-redirect/interact?account=ligon&repo=HackingFood&branch=master&path=) in order to access the dataset (Tanzanian NPS folder --> tanzanian_nps.ds). Thank you!

**Comment by julie-tran** [comment] 2019-05-01 22:05
The file fct-full-fct-full.csv is now uploaded. Thanks for letting us know!

**Comment by liandy52** [comment] 2019-05-01 22:07
> I believe this is a different issue than the one mentioned in the heading above^. The dataset, "TanzanianNPS/tanzanian_nps.ds", is too large to upload to GitHub. Please follow this [link ](http://datahub.berkeley.edu/user-redirect/interact?account=ligon&repo=HackingFood&branch=master&path=) in order to access the dataset (Tanzanian NPS folder --> tanzanian_nps.ds). Thank you!

Thanks for your response. 
I was observed that as long as the data set is existed in the same repository, then it should not be a problem of opening it. So I don't think that's the reason here. Maybe you should upload the data set in the same repository? :)

**Comment by liandy52** [comment] 2019-05-01 22:12
> The file fct-full-fct-full.csv is now uploaded. Thanks for letting us know!

There is still an error, "b'/home/jovyan/eep153-proj4/TanzanianNPS/tanzanian_nps.ds' files are not found.

**Comment by jnuesca** [comment] 2019-05-01 22:37
> > The file fct-full-fct-full.csv is now uploaded. Thanks for letting us know!
> 
> There is still an error, "b'/home/jovyan/eep153-proj4/TanzanianNPS/tanzanian_nps.ds' files are not found.

Hi lindy52, 

Are you trying to run this on Jupyter/Datahub, or Colab? For best performance, I would recommend downloading the .ipynb and associated dependencies (.csv/.ds) and uploading it to your personal datahub. Hopefully this fixes your issue.

**Closed as completed** 2019-05-01 23:02 UTC
